testing(project) ::= <<
[Home](Home) > [Testing](testing) > Java

Just run `gradle test`:

```
% gradle test
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:compileTestJava
:processTestResources
:testClasses
:test

BUILD SUCCESSFUL

Total time: 6.173 secs
```

[liblevenshtein](https://github.com/universal-automata/liblevenshtein) is maintained by [@dylon](https://github.com/dylon)
>>
/* vim: set ft=ghmarkdown: */
