#!/usr/bin/env bash

set -ev

source "$(dirname "$0")/functions"

which node || fail "node is not installed"
which npm || fail "npm is not installed"

declare -r CSSLINT_HOME="${CSSLINT_HOME:-$HOME}"
declare -r CSSLINT_CLI_JS="$CSSLINT_HOME/node_modules/csslint/cli.js"

node "$CSSLINT_CLI_JS" --ignore=overqualified-elements,box-sizing "$@"

# vim: set ft=sh ts=2 sw=2 et sta:
