#!/usr/bin/env bash

set -ev

source "$(dirname "$0")/functions"

assert-changes-committed
assert-release-version "$(project-version)"
assert-versions-equal 'latestVersion' "$(project-version)" "$(latest-version)"
assert-versions-equal 'gitBranch' "$(project-version)" "$(project-branch)"
assert-release-notes
print-project-version
clean-check
update-readme
update-wikidoc-javadoc
update-branch 'release'
update-branch 'release-3.x'
tag-release
update-java-submodule
succeed

# vim: set ft=sh ts=2 sw=2 et sta:
